version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/cicd
    overwrite: yes

file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ec2-user/cicd/scripts/*.sh
    mode: "755"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 180
      runas: ec2-user

  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 180
      runas: ec2-user
