version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/cicd/scripts/*
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 180
      runas: root

  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 180
      runas: root
