version: '3.8'
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "80:80/tcp"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/fundina.shop/fullchain.pem:/etc/ssl/certs/fullchain.pem
      - /etc/letsencrypt/live/fundina.shop/privkey.pem:/etc/ssl/private/privkey.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/nginx/snippets/options-ssl-nginx.conf
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/ssl/certs/ssl-dhparams.pem
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - app1
      - app2
      - app3

  app1:
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    environment:
      MYSQL_URL: "${MYSQL_URL}"
      MYSQL_USERNAME: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always
    container_name: "app1"

  app2:
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    environment:
      MYSQL_URL: "${MYSQL_URL}"
      MYSQL_USERNAME: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always
    container_name: "app2"

  app3:
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    environment:
      MYSQL_URL: "${MYSQL_URL}"
      MYSQL_USERNAME: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always
    container_name: "app3"

  certbot: # certbot 서비스 추가
    image: certbot/certbot
    container_name: certbot_service
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"