version: '3.8'
services:
  app1:
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    ports:
      - "8081:8080"
    environment:
      MYSQL_URL: "${MYSQL_URL}"
      MYSQL_USERNAME: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always

  app2:
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    ports:
      - "8082:8080"
    environment:
      MYSQL_URL: "${MYSQL_URL}"
      MYSQL_USERNAME: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always

  app3:
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    ports:
      - "8083:8080"
    environment:
      MYSQL_URL: "${MYSQL_URL}"
      MYSQL_USERNAME: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    restart: always
