spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  flyway:
    enabled: false
    baseline-on-migrate: false

  sql:
    init:
      mode: always
      data-locations: classpath:testdata/initial_category_brand_product.sql

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true





logging:
  level:
    org.org.hibernate.SQL: debug
    org.hibernate.type: trace


