management:
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    metrics:
      enabled: true
  endpoints:
    web:
      exposure:
        include: beans, conditions, mappings, info, health, prometheus
        exclude: heapdump, env
  metrics:
    tags:
      application: ${spring.application.name}
