CREATE TABLE brand
(
    brand_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    name       VARCHAR(255)                            NOT NULL,
    icon_photo VARCHAR(255),
    CONSTRAINT pk_brand PRIMARY KEY (brand_id)
);

CREATE TABLE category
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    name        VARCHAR(255)                            NOT NULL,
    parent_id   BIGINT,
    CONSTRAINT pk_category PRIMARY KEY (category_id)
);

CREATE TABLE funding
(
    funding_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP,
    status            VARCHAR(255),
    expired_at        date                                    NOT NULL,
    goal_amount       BIGINT                                  NOT NULL,
    accumulate_amount BIGINT                                  NOT NULL,
    member_id         BIGINT                                  NOT NULL,
    product_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_funding PRIMARY KEY (funding_id)
);

CREATE TABLE funding_detail
(
    funding_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP,
    amount            DECIMAL(12, 2)                          NOT NULL,
    rate              DECIMAL(7, 2)                           NOT NULL,
    funding_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_fundingdetail PRIMARY KEY (funding_detail_id)
);

CREATE TABLE gift
(
    gift_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP,
    updated_at    TIMESTAMP,
    status        VARCHAR(50)                             NOT NULL,
    message       VARCHAR(255),
    message_photo VARCHAR(255),
    orders_id     BIGINT                                  NOT NULL,
    product_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_gift PRIMARY KEY (gift_id)
);

CREATE TABLE hashtag
(
    hashtag_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    name       VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_hashtag PRIMARY KEY (hashtag_id)
);

CREATE TABLE member
(
    member_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP,
    updated_at   TIMESTAMP,
    gender       VARCHAR(255)                            NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    phone_number VARCHAR(20)                             NOT NULL,
    provider_id  VARCHAR(255)                            NOT NULL,
    role         VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_member PRIMARY KEY (member_id)
);

CREATE TABLE option_detail
(
    option_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at       TIMESTAMP,
    updated_at       TIMESTAMP,
    name             VARCHAR(255)                            NOT NULL,
    stock_quantity   INT                                     NOT NULL,
    additional_price BIGINT                                  NOT NULL,
    photo            VARCHAR(255),
    option_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_optiondetail PRIMARY KEY (option_detail_id)
);

CREATE TABLE options
(
    options_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    name       VARCHAR(255)                            NOT NULL,
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_options PRIMARY KEY (options_id)
);

CREATE TABLE orders
(
    orders_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP,
    stock_quantity    INT                                     NOT NULL,
    order_number      VARCHAR(10)                             NOT NULL,
    status            VARCHAR(255)                            NOT NULL,
    member_id         BIGINT                                  NOT NULL,
    funding_detail_id BIGINT,
    payment_id        BIGINT,
    product_id        BIGINT                                  NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (orders_id)
);

CREATE TABLE payment
(
    payment_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at     TIMESTAMP,
    updated_at     TIMESTAMP,
    method         VARCHAR(255)                            NOT NULL,
    total_price    BIGINT                                  NOT NULL,
    purchase_price BIGINT                                  NOT NULL,
    delivery_price BIGINT                                  NOT NULL,
    CONSTRAINT pk_payment PRIMARY KEY (payment_id)
);

CREATE TABLE product
(
    product_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP,
    name              VARCHAR(255)                            NOT NULL,
    price             BIGINT                                  NOT NULL,
    type              VARCHAR(50)                             NOT NULL,
    photo             VARCHAR(255),
    category_id       BIGINT                                  NOT NULL,
    brand_id          BIGINT                                  NOT NULL,
    product_detail_id BIGINT,
    wish_count        INT,
    order_count       INT,
    brand_name        VARCHAR(255),
    CONSTRAINT pk_product PRIMARY KEY (product_id)
);

CREATE TABLE product_description_photo
(
    photo_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    photo_url  VARCHAR(255),
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_productdescriptionphoto PRIMARY KEY (photo_id)
);

CREATE TABLE product_detail
(
    product_detail_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP,
    updated_at          TIMESTAMP,
    description         CLOB                                    NOT NULL,
    has_photo           BOOLEAN                                 NOT NULL,
    product_name        VARCHAR(255)                            NOT NULL,
    origin              VARCHAR(255)                            NOT NULL,
    manufacturer        VARCHAR(255)                            NOT NULL,
    tel                 VARCHAR(20)                             NOT NULL,
    deliver_description CLOB                                    NOT NULL,
    billing_notice      CLOB                                    NOT NULL,
    caution             CLOB                                    NOT NULL,
    CONSTRAINT pk_productdetail PRIMARY KEY (product_detail_id)
);

CREATE TABLE product_hashtag
(
    product_hashtag_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at         TIMESTAMP,
    updated_at         TIMESTAMP,
    hashtag_id         BIGINT                                  NOT NULL,
    product_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_producthashtag PRIMARY KEY (product_hashtag_id)
);

CREATE TABLE product_thumbnail
(
    product_thumbnail_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at           TIMESTAMP,
    updated_at           TIMESTAMP,
    thumbnail_url        VARCHAR(255),
    product_id           BIGINT                                  NOT NULL,
    CONSTRAINT pk_productthumbnail PRIMARY KEY (product_thumbnail_id)
);

CREATE TABLE theme
(

    theme_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    photo       VARCHAR(255)                            NOT NULL,
    description CLOB                                    NOT NULL,
    CONSTRAINT pk_theme PRIMARY KEY (theme_id)
);

CREATE TABLE wish
(
    wish_id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    is_public  BOOLEAN                                 NOT NULL,
    product_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_wish PRIMARY KEY (wish_id)
);

ALTER TABLE category
    ADD CONSTRAINT FK_CATEGORY_ON_PARENT FOREIGN KEY (parent_id) REFERENCES category (category_id);

ALTER TABLE funding_detail
    ADD CONSTRAINT FK_FUNDINGDETAIL_ON_FUNDING FOREIGN KEY (funding_id) REFERENCES funding (funding_id);

ALTER TABLE funding
    ADD CONSTRAINT FK_FUNDING_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE funding
    ADD CONSTRAINT FK_FUNDING_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

ALTER TABLE gift
    ADD CONSTRAINT FK_GIFT_ON_ORDERS FOREIGN KEY (orders_id) REFERENCES orders (orders_id);

ALTER TABLE gift
    ADD CONSTRAINT FK_GIFT_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

ALTER TABLE option_detail
    ADD CONSTRAINT FK_OPTIONDETAIL_ON_OPTION FOREIGN KEY (option_id) REFERENCES options (options_id);

ALTER TABLE options
    ADD CONSTRAINT FK_OPTIONS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_FUNDING_DETAIL FOREIGN KEY (funding_detail_id) REFERENCES funding_detail (funding_detail_id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_MEMBER FOREIGN KEY (member_id) REFERENCES member (member_id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_PAYMENT FOREIGN KEY (payment_id) REFERENCES payment (payment_id);

ALTER TABLE orders
    ADD CONSTRAINT FK_ORDERS_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

ALTER TABLE product_description_photo
    ADD CONSTRAINT FK_PRODUCTDESCRIPTIONPHOTO_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

ALTER TABLE product_hashtag
    ADD CONSTRAINT FK_PRODUCTHASHTAG_ON_HASHTAG FOREIGN KEY (hashtag_id) REFERENCES hashtag (hashtag_id);

ALTER TABLE product_hashtag
    ADD CONSTRAINT FK_PRODUCTHASHTAG_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

ALTER TABLE product_thumbnail
    ADD CONSTRAINT FK_PRODUCTTHUMBNAIL_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_BRAND FOREIGN KEY (brand_id) REFERENCES brand (brand_id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES category (category_id);

ALTER TABLE product
    ADD CONSTRAINT FK_PRODUCT_ON_PRODUCT_DETAIL FOREIGN KEY (product_detail_id) REFERENCES product_detail (product_detail_id);

ALTER TABLE wish
    ADD CONSTRAINT FK_WISH_ON_PRODUCT FOREIGN KEY (product_id) REFERENCES product (product_id);
