ALTER TABLE member
    MODIFY gender VARCHAR(255) NOT NULL;

ALTER TABLE payment
    MODIFY method VARCHAR(255) NOT NULL;

ALTER TABLE member
    MODIFY `role` VARCHAR(255) NOT NULL;

ALTER TABLE orders
    MODIFY status VARCHAR(255) NOT NULL;